#version: "4.33"

name: banking_db_and_kafka_stack

services:
  db-server:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    container_name: db-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=banking
    volumes:
      - /tmp/postgres-db-server:/var/lib/postgresql

  kafka-server1:
    image: 'bitnami/kafka:latest'
    ports:
      - "9082:9082"
    container_name: kafka-server1
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=kafkacluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-server1:9081,2@kafka-server2:9081,3@kafka-server3:9081
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9080,CONTROLLER://:9081,EXTERNAL://:9082
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server1:9080,EXTERNAL://${HOSTNAME:-localhost}:9082
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /tmp/kafka/kafka-server1:/bitnami/kafka

  kafka-server2:
    image: 'bitnami/kafka:latest'
    ports:
      - "9083:9082"
    container_name: kafka-server2
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=kafkacluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-server1:9081,2@kafka-server2:9081,3@kafka-server3:9081
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9080,CONTROLLER://:9081,EXTERNAL://:9082
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server2:9080,EXTERNAL://${HOSTNAME:-localhost}:9082
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /tmp/kafka/kafka-server2:/bitnami/kafka

  kafka-server3:
    image: 'bitnami/kafka:latest'
    ports:
      - "9084:9082"
    container_name: kafka-server3
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=kafkacluster
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-server1:9081,2@kafka-server2:9081,3@kafka-server3:9081
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9080,CONTROLLER://:9081,EXTERNAL://:9082
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server3:9080,EXTERNAL://${HOSTNAME:-localhost}:9082
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - /tmp/kafka/kafka-server3:/bitnami/kafka