drop table if exists banking.account cascade;

create table banking.account
(
    id           integer generated by default as identity,
    money_amount integer,
    user_id      integer,
    status_id       integer REFERENCES banking.dict_account_status (id),
    primary key (id)
);